language: perl
perl:
    - '5.18'
env:
    - BACKEND=moar
    - BACKEND=jvm # Need to setup jdk?
    - BACKEND=parrot 
matrix:
    allow_failures:
        - env: BACKEND=jvm
        - env: BACKEND=parrot
    fast_finish: true
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND # We could do all backends here; but it would take forever
    - perl6 -v
    - rakudobrew build-panda  # Maybe skip installing panda and 
install:
    - panda --notests install . # installs deps
before_script:
    - pandabrew panda list --installed --verbose # maybe make this a test module like Dist::Zilla::Plugin::ReportVersions
script:
    - prove -e perl6 -lrv t/ 
after_success:
#   do coveralls.io testing
notifications:
    recipients:
        - ugexe@cpan.org
    email:
        on_success: change
        on_failure: always