language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar PANDA_SUBMIT_TESTREPORTS=yes
    - BACKEND=jvm PANDA_SUBMIT_TESTREPORTS=yes
    - BACKEND=parrot
matrix:
    allow_failures:
        - env: BACKEND=jvm
        - env: BACKEND=parrot
    fast_finish: true
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init # helpers for parallel testing/testing dirs
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
    - perl6 -v
    - rakudobrew build-panda
    - panda install XML
    - panda look XML::Query
    - panda-build
    - perl6 -Ilib --target=mbc --output=blib/lib/XML/Query.moarvm lib/XML/Query.pm6
    - prove -v -s -j$(test-jobs) -e "perl6 --ll-exception -Iblib/lib -Ilib" $(test-files)
    - panda list --installed --verbose # modules installed before panda-install
after_success:
    - panda list --installed --verbose # modules installed after panda-install
#   do coveralls.io testing?
