language: perl
perl:
- '5.18'
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build moar
    - rakudobrew build-panda  # Maybe skip installing panda and 
    - panda install pandabrew # just build pandabrew direct from repo?
    - ~/.rakudobrew/moar-HEAD/install/languages/perl6/site/bin/pandabrew init # todo: pandabrew path in $PATH
install:
    - panda --notests install . # installs deps
before_script:
    - panda list --installed --verbose # maybe make this a test module like Dist::Zilla::Plugin::ReportVersions
script:
    - prove -e perl6 -lrv t/ 
after_success:
#   do coveralls.io testing
notifications:
    recipients:
        - ugexe@cpan.org
    email:
        on_success: change
        on_failure: always