language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar PANDA_SUBMIT_TESTREPORTS=yes
    - BACKEND=jvm PANDA_SUBMIT_TESTREPORTS=yes
    - BACKEND=parrot
matrix:
    allow_failures:
        - env: BACKEND=jvm
        - env: BACKEND=parrot
    fast_finish: true
before_install:
    - 'if [ "$BACKEND" == "parrot" ]; then sudo apt-get update -qq; fi;'
    - 'if [ "$BACKEND" == "parrot" ]; then sudo apt-get install -qq libicu48 libicu-dev; fi;'
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init # helpers for parallel testing/testing dirs
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
    - perl6 -v
    - rakudobrew build-panda # install some deps for source install
before_script:
    - panda list --installed --verbose # modules installed before panda-install
script:
    - PANDA_SUBMIT_TESTREPORTS=yes panda install .
after_success:
    - panda list --installed --verbose # modules installed after panda-install
