language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar
    - BACKEND=jvm
    - BACKEND=parrot
matrix:
    allow_failures:
        - env: BACKEND=jvm
        - env: BACKEND=parrot
    fast_finish: true
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init # helpers for parallel testing/testing dirs
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
    - perl6 -v
    - rakudobrew build-panda # install some deps for source install
    - git clone https://github.com/tadzik/panda --branch reporter --depth 1 ~/panda
    - (cd ~/panda && perl6 rebootstrap.pl)
    - PANDA_SUBMIT_TESTREPORTS=yes
install:
    - panda-fetch .
    - panda-build
before_script:
    - panda list --installed --verbose # modules installed before panda-install
script:
    - prove -v -s -j$(test-jobs) -e "perl6 --ll-exception -Ilib" $(test-files)
    - panda-test
    - panda-install
after_success:
    - panda list --installed --verbose # modules installed after panda-install
#   do coveralls.io testing?
