language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar
    - BACKEND=jvm
    - BACKEND=parrot
matrix:
    allow_failures:
        - env: BACKEND=jvm
        - env: BACKEND=parrot
    fast_finish: true
before_install:
    # parrot requires ICU
    - 'if [ "$BACKEND" == "parrot" ]; then sudo apt-get update -qq; fi;'
    - 'if [ "$BACKEND" == "parrot" ]; then sudo apt-get install -qq libicu48 libicu-dev; fi;'
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
    - perl6 -v
    - rakudobrew build-panda
before_script:
    - panda list --installed --verbose # modules installed before panda-install
script:
    # tests that module passes tests *before* compile
    - PANDA_SUBMIT_TESTREPORTS=yes panda install .
after_success:
    # modules installed before panda-install
    - panda list --installed --verbose
